Added synchronous counter interactive example
CircuitVerse/Interactive-Book pull request #128
Opened 2019-12-14 15:52 UTC by fluctix

Solves #116 
[GCI Task](https://codein.withgoogle.com/dashboard/task-instances/4677084887121920/)

https://circuitverse.org/simulator/embed/43082

Screenshots:
![embedSCshot](https://user-images.githubusercontent.com/40538506/70846678-cdc3d800-1e81-11ea-8f00-4702e3c4b35f.PNG)

2019-12-14 16:02 UTC, fluctix commented
@sal2701 @PragatiVerma18 @sakshi1499 Please review.

2019-12-14 18:01 UTC, Ananthavijay commented
@fluctix I think you can also fix the broken image under Synchronous counters ( At last )

2019-12-14 18:45 UTC, sakshi1499 commented
@fluctix It looks good to me. @Ananthavijay which image are you talking about can you attach a screenshot? I can't see any broken image in my fork

2019-12-14 18:45 UTC, sakshi1499 commented
@PragatiVerma18 @sal2701 please look at it once?

2019-12-14 18:56 UTC, Ananthavijay commented
@sakshi1499 This is the one I am talking about.

![Screenshot (103)](https://user-images.githubusercontent.com/35162705/70853258-7baaa300-1ed1-11ea-85ac-c747846bccfb.png)

2019-12-14 18:59 UTC, sakshi1499 commented
![Screenshot_20191215-002814](https://user-images.githubusercontent.com/42520146/70853285-e065fd80-1ed1-11ea-8bc8-d393911bbf51.png)


See its fine in mine!

2019-12-14 19:00 UTC, Ananthavijay commented
@sakshi1499 check it here : https://github.com/CircuitVerse/Interactive-Book/blob/master/docs/counter.md

2019-12-14 19:04 UTC, sakshi1499 commented
Yes I have seen. The image is broken on Github .md page, its working fine on the website. Please edit that too @fluctix

2019-12-14 21:22 UTC, sal2701 requested changes
@fluctix One more small detail, can you just rename the circuit appropriately. **Main** is written on the top left, please change it.

2019-12-14 21:26 UTC, sal2701 commented
@sakshi1499 I think we should show 2 outputs, **Qa** and **Qb** as it'll better demonstrate the 2 Bit Counter. A single output here is confusing. What say?

2019-12-15 01:47 UTC, fluctix commented
Updated the Markdown file to point to the correct location of the Image(as requested by @Ananthavijay ) and also as @sal2701 suggested, I renamed the circuit from 'main' to 'Synchronous Counter' , and added one more output(ie. Qa) for better understanding.
Screenshots:
![Screenshot1](https://user-images.githubusercontent.com/40538506/70856902-b54bd000-1f0a-11ea-905e-341eb09a4ee8.PNG)
![Screenshot2](https://user-images.githubusercontent.com/40538506/70856903-b54bd000-1f0a-11ea-92ce-88dcf088914c.PNG)

2019-12-15 01:47 UTC, fluctix commented
@sakshi1499 @sal2701 Please review.

2019-12-15 04:55 UTC, PragatiVerma18 commented
Looks good to me!! Great work @fluctix 😃

2019-12-15 04:56 UTC, PragatiVerma18 approved these changes

2019-12-15 09:11 UTC, sakshi1499 commented
Great work!. @sal2701 that was a good suggestion.

2019-12-15 09:11 UTC, sakshi1499 approved these changes

2019-12-15 09:12 UTC, sakshi1499 commented
@sal2701 Please look at it if you find no issues please approve it?

2020-01-16 12:02 UTC, fluctix commented
New changes have brought merge conflicts....

2020-05-16 04:24 UTC, Shivansh2407 commented
@criticic can you please fix the merge conflicts?

2026-05-26 15:44 UTC, magic-peach commented
This PR has been open since 2019-2020 and the repo has changed significantly since then. Closing as stale.

2026-05-26 15:44 UTC, closed without merging