Added buttons to get anchor links
CircuitVerse/Interactive-Book pull request #147
Opened 2019-12-23 03:24 UTC by nrs1729

Created a button that copies the anchor link to the current location into the clipboard. 

Screenshots:
![image](https://user-images.githubusercontent.com/51863168/71333769-3f132300-2533-11ea-9a12-134ebd3c6879.png)

On hover:
![image](https://user-images.githubusercontent.com/51863168/71333852-9f09c980-2533-11ea-9dee-4c81c4d8114b.png)

2019-12-25 18:04 UTC, sal2701 requested changes
Take a look at the dashboard

2019-12-30 21:36 UTC, sal2701 approved these changes
Great work!

2020-05-15 11:35 UTC, Shivansh2407 commented
Please resolve the merge conflicts @nrs1729

2026-05-26 15:44 UTC, magic-peach commented
This PR has been open since 2019-2020 and the repo has changed significantly since then. Closing as stale.

2026-05-26 15:51 UTC, magic-peach commented
This PR has been open since 2019-2020 and the repo has changed significantly since then. Closing as stale.

2026-05-26 15:51 UTC, closed without merging