minor change
CircuitVerse/Interactive-Book pull request #222
Opened 2020-01-24 16:08 UTC by prabhleenkaur1007

did minor changes, which are easy to ignore but better be corrected :-))

2020-01-24 16:42 UTC, Ananthavijay commented
@prabhleenkaur1007 add scrennshots of the change.

2020-01-24 19:29 UTC, aayush-05 commented
Adding a descriptive title and description along with some screenshots would have us to review it better @prabhleenkaur1007

2020-01-24 20:03 UTC, prabhleenkaur1007 commented
> @prabhleenkaur1007 adding screenshots of the change would be helpful.

for the first commit, the change is only in the width of the top two buttons. the files are: before and after
![before](https://user-images.githubusercontent.com/43867458/73099731-14d9ca00-3f12-11ea-820a-bab89a008d74.png)
![after](https://user-images.githubusercontent.com/43867458/73099767-26bb6d00-3f12-11ea-9afd-9e19cb02437e.png)

for the second commit, the change is in the alignment of the link "combinational circuits".the files are: before2 and second2
![before2](https://user-images.githubusercontent.com/43867458/73099800-418de180-3f12-11ea-82f3-a1e0862e538e.png)
![after2](https://user-images.githubusercontent.com/43867458/73099831-4eaad080-3f12-11ea-814f-f9716ae58635.png)

let me know, if it is helpful.
 i would love to contribute more.

2020-01-24 23:36 UTC, JoshHeng commented
Update commit title and description to consisely say what you have changed. Some commit messages should also be more specific, and use capital letters. Also follow Hound's instructions.

2020-01-25 01:59 UTC, Ananthavijay commented
@prabhleenkaur1007 overlap of breadcrumb nav is not the Only problem. Try opening and closing the sidebar by clicking the sudebar button, breadcrumb nav would not move

2020-01-25 13:52 UTC, prabhleenkaur1007 commented
my sincere apologies for the delay in reply.

the commit, "ADDED DISCUS.HTML" was done because many pages are missing the last column. i will also commit this change for remaining other pages(which are missing this) soon.
![discus](https://user-images.githubusercontent.com/43867458/73122090-a2ff9000-3fa6-11ea-8968-869bec12e5a0.png)

the commit, "MADE THE LINKS WORKING" is very clear i think. Before and After screenshots are below.
![reference](https://user-images.githubusercontent.com/43867458/73122143-6aac8180-3fa7-11ea-988e-91de0614254c.png)
![reference2](https://user-images.githubusercontent.com/43867458/73122144-76984380-3fa7-11ea-8fa4-e9246871973d.png)

2020-01-25 14:45 UTC, aayush-05 commented
@prabhleenkaur1007 you are not supposed to add so many changes in one single pr. Make separate prs to solve various issues with proper title, description and screenshots. Also, please check before solving an issue if it has been solved before, check standing prs and try claiming a task before working on it.

2020-01-25 14:56 UTC, Ananthavijay commented
@prabhleenkaur1007 I have already fixed the overlapping issue in this [PR](https://github.com/CircuitVerse/Interactive-Book/pull/217). First create a issue on it and then start working on the bug/feature

2020-01-26 06:27 UTC, prabhleenkaur1007 commented
@aayush-05 and @Ananthavijay, i will abide by the instructions in the future. THANK YOU
This is my first contribution to such an amazingly huge community.

2020-05-20 03:54 UTC, YashKumarVerma requested changes
check merge conflicts

2026-05-26 15:44 UTC, magic-peach commented
This PR has been open since 2019-2020 and the repo has changed significantly since then. Closing as stale.

2026-05-26 15:51 UTC, magic-peach commented
This PR has been open since 2019-2020 and the repo has changed significantly since then. Closing as stale.

2026-05-26 15:51 UTC, closed without merging