Remove kmap layout and instead use default layout
CircuitVerse/Interactive-Book pull request #224
Opened 2020-01-25 18:28 UTC by mohit-003

The kmap layout is removed, and the default layout is used instead of it in Intractive Karnaugh Map page, and some dark-mode issues of the same page are resolved.

2020-01-25 18:35 UTC, mohit-003 commented
@tachyons Please review.

2020-02-20 16:37 UTC, aayush-05 commented
This looks good, but I am not very sure if we are currently switching to a central default layout for all pages. Also I will have to check that it is not affecting other pages.

2020-02-20 16:42 UTC, mohit-003 commented
I checked all other pages and only the K-map page used kmap layout and all other pages are using the default layout.

2020-05-20 04:00 UTC, YashKumarVerma requested changes
not the correct way to change layout

2020-05-21 06:53 UTC, ShubhankarKG commented
Resolved in #297 . @YashKumarVerma can be closed.

2026-05-26 15:51 UTC, magic-peach commented
This PR has been open since 2019-2020 and the repo has changed significantly since then. Closing as stale.

2026-05-26 15:51 UTC, closed without merging