Added simulations of JK and T latches
CircuitVerse/Interactive-Book pull request #336
Opened 2020-05-21 10:23 UTC by Dishebh

#### Changes done:
- [x] Added simulations of JK and T latches

#### Screenshots
![Screenshot from 2020-05-21 15-52-28](https://user-images.githubusercontent.com/43489708/82549821-29099d00-9b7b-11ea-924d-73db15694da2.png)
![Screenshot from 2020-05-21 15-52-33](https://user-images.githubusercontent.com/43489708/82549838-2f981480-9b7b-11ea-8c4f-a01192c596d3.png)

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add a link from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2020-05-21 11:10 UTC, Shivansh2407 requested changes
Please Update the Circuits with the Clock, And replace ConstantVal with Input. Let me know your views @YashKumarVerma 👍

2020-05-21 11:20 UTC, Dishebh commented
> Please Update the Circuits with the Clock, And replace ConstantVal with Input. Let me know your views @YashKumarVerma

Latches do not have clock signal as one of their inputs. Also, all other latches have a constant value as an input. Shall I replace all of them?

2020-05-21 11:36 UTC, Shivansh2407 commented
Pleas go through T latch in the Link : https://www.elprocus.com/basics-of-latches-in-digital-electronics/
JK Latch : https://www.electronics-tutorials.ws/sequential/seq_2.html

2020-05-21 11:42 UTC, Dishebh commented
@Shivansh2407 I referred to this link: https://www.edgefx.in/digital-electronics-latches-and-flip-flops/
Pls check out 2nd paragraph 2nd line.

2020-05-22 06:55 UTC, Dishebh commented
@Shivansh2407 Pls refer this article as well
https://en.wikipedia.org/wiki/Flip-flop_(electronics)#JK_latch
Neither of the diagrams have clock as their input. Some have Enable (E), but not clock.

2020-05-23 07:04 UTC, Dishebh commented
@Shivansh2407 @YashKumarVerma thoughts?

2020-06-11 06:39 UTC, Dishebh commented
@Shivansh2407 @YashKumarVerma please review

2020-06-11 07:23 UTC, YashKumarVerma commented
> @Shivansh2407 @YashKumarVerma please review

JK latch needs to have a clock associated with it, which ensures that the condition is checked periodically.

2020-06-11 07:31 UTC, Dishebh commented
> > @Shivansh2407 @YashKumarVerma please review
> 
> JK latch needs to have a clock associated with it, which ensures that the condition is checked periodically.

Cool, I'll add the clock, then :)

2020-06-11 17:09 UTC, Dishebh commented
@YashKumarVerma Just one small doubt here,
![Screenshot from 2020-06-11 22-36-54](https://user-images.githubusercontent.com/43489708/84418156-5d312480-ac34-11ea-8bae-c171d606f3da.png)

If I add the clock to the JK latch here, wouldn't it make it the JK flip-flop? (from the diagram above)

Also, If I were to add the clock nevertheless, should I add it to both the latches?

2026-05-26 15:44 UTC, magic-peach commented
This PR has been open since 2019-2020 and the repo has changed significantly since then. Closing as stale.

2026-05-26 15:45 UTC, closed without merging