Verilog Operators
CircuitVerse/Interactive-Book pull request #370
Opened 2020-05-26 13:08 UTC by eKuG

A meaningful title for PR, not like: made changes to xyz.md

Fixes #

Ref #

#### Changes done:
- [x] Task 1

#### Screenshots

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [ ] Checked to see if a similar PR has already been opened 🤔️
- [ ] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

2020-05-26 13:09 UTC, eKuG commented
Will be used in a later PR. Please merge @Shivansh2407

2020-05-26 16:08 UTC, YashKumarVerma commented
> Will be used in a later PR. Please merge @Shivansh2407

Please fill up the PR Template

2020-05-26 17:06 UTC, Dishebh requested changes
Please see why the checks are failing

2020-05-27 13:00 UTC, mahmodHammad commented
This is just an image, that's why checks are falling

2020-05-27 13:03 UTC, mahmodHammad commented
i think you should add it directly to your other PR where you need it without creating a separate PR for it.

you can update any PR as simple as this:
Move to the branch of the  PR in your machine, add the image , commit , push

2026-05-26 15:45 UTC, magic-peach commented
This PR has been open since 2019-2020 and the repo has changed significantly since then. Closing as stale.

2026-05-26 15:45 UTC, closed without merging