Added truth tables for demux
CircuitVerse/Interactive-Book pull request #432
Opened 2020-06-09 07:28 UTC by Dishebh

#### Changes done:
- [x] Added truth tables for demux

#### Screenshots

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2020-06-09 10:01 UTC, Shivansh2407 requested changes
Please remove Block Diagram from TOC @Dishebh 👍. Also please let me know your views on making the table as it was implemented in the mix page. Is there any specific reason of using HTML table tags here?

2020-06-09 10:44 UTC, Dishebh commented
@Shivansh2407 the tables had a complex structure here (if you compare it with the other tables) as it had nested inputs and outputs, similar to `jk_race_around_condition` table. And so, I used the table tags and implemented it this way.

2020-06-11 06:20 UTC, Dishebh commented
please review @Shivansh2407 @YashKumarVerma :)

2020-06-11 06:39 UTC, Shivansh2407 requested changes
Please Shadow Effect to each and every side of the Table . Take reference from the Race around Condition Page. Currently the shadow is available in the bottom of the tables and side borders are there only for the second row of each table. You need to remove that left border from first column of second row and add shadow effects to each side to complete the table.
Please make the suggested changes @Dishebh 👍

2020-06-11 06:42 UTC, Shivansh2407 commented
Have a look at the image below : 
Current Table :
![image](https://user-images.githubusercontent.com/42182955/84353336-9473e700-abdc-11ea-9837-2f4e66fb737f.png)
Race Around Page Table : 
![image](https://user-images.githubusercontent.com/42182955/84353404-b4a3a600-abdc-11ea-9b0d-6964e5c19f9e.png)

2020-06-11 17:03 UTC, Dishebh commented
@Shivansh2407 made the box-shadow same as jk_race_around_condition truth table :)

2020-06-12 04:47 UTC, Shivansh2407 commented
@Dishebh Please look at the 1:8 and 1:16 table as these are horizontally long and in desktop view no horizontal scrolling is enabled. Try to implement the horizontal scroll in these two tables so that the user can view the rest of the table.

2020-06-12 06:19 UTC, Dishebh commented
@Shivansh2407 I hope it fixes the scrolling issue now

2020-06-12 06:59 UTC, Shivansh2407 commented
> @Shivansh2407 I hope it fixes the scrolling issue now

The scrolling issue is fixed but the problem now is a white space that is added to each and every table . Just fix this and we will be ready to merge this @Dishebh 👍 

Have a look at the image below : 
![image](https://user-images.githubusercontent.com/42182955/84474331-488e7400-aca8-11ea-9889-ef86330891c4.png)

2020-06-12 09:55 UTC, Dishebh commented
@Shivansh2407 removed extra space below tables

2020-06-12 10:02 UTC, Shivansh2407 commented
@Dishebh the thing is I want you to make margin bottom available for the tables with scrolling as it was earlier. For tables without scroll bar remove that thing. Also in the recent commit, you have removed the spacing between the Truth table and the circuit. Please fix that. If you have any questions, please let me know.

2020-06-12 14:07 UTC, YashKumarVerma requested changes
Check hound errors

2020-06-12 18:02 UTC, Dishebh commented
@Shivansh2407 I have set the `overflow` property of table to `auto`, and the `margin-bottom` to `0`. This ensures that:

- The scroll-bar gets automatically added to the table, depending upon the screen resolution and size. 
- The extra space visible at the bottom of the table gets vanished and resolves the issue:
> The scrolling issue is fixed but the problem now is a white space that is added to each and every table.

So it would be hard to determine which table has scroll-bar and which has not, as it will never be a fixed bool. And if I add a `margin-bottom`, it will again give rise to the previous issue.

2020-06-15 08:07 UTC, YashKumarVerma requested changes
Check hound issues.

2026-05-26 15:45 UTC, magic-peach commented
This PR has been open since 2019-2020 and the repo has changed significantly since then. Closing as stale.

2026-05-26 15:45 UTC, closed without merging