Accessibility Enhancement as per WCAG2.0 standards for 'Clock Signal and Triggering' page
CircuitVerse/Interactive-Book pull request #452
Opened 2020-07-18 22:20 UTC by schezfaz

**Enhancement:**  Rendered the content on the [Clock Signal and Triggering](https://learn.circuitverse.org/docs/clock.html) page more accessible by making its content structure a11y compliant as per [WCAG2](https://www.w3.org/TR/WCAG20/) standards.

Ref #80  (removed plagiarism as part of revamp)

#### Changes done as per a11y guidelines:
- [x] Gave the page URL a more meaningful link:
The URL of a page conveys a lot of information and thus making the URL link for the page standardised in accordance to the page title is a better practise.
   - Changed the url from `.../docs/clock.html `to `.../docs/ClockSignalAndTriggering.html`

- [x] Represented all numbers as digits:
It is easier for the reader to consume the sentence when numbers are represented as numbers and not spelt out. 
  - Changed "Two types of triggering" to "2 types of triggering" and in similar applicable places

- [x] Used consistent, simplified tone and grammatical structure:
Accessibility standards state that content should be written in a simplified manner. All similar content (such as information cited in a list, or similar examples) should have a consistent flow.
   - For example, standardarised the content structure for types of Edge triggering and Level triggering respectively.

- [x] Replaced bulleted lists with numbered lists
**Before:**
![image](https://user-images.githubusercontent.com/28871211/87862780-759e0880-c971-11ea-833d-3cd3894c84a7.png)
**After:**
![image](https://user-images.githubusercontent.com/28871211/87862782-80f13400-c971-11ea-8719-a42240417dbe.png)

- [x] Removed unnecessary bold/italic highlights and used them only when emphasis was required.
       eg. : Removed bold highlight on "logic high" as it does not need emphasis with reference to context
![image](https://user-images.githubusercontent.com/28871211/87862826-d7f70900-c971-11ea-9ec5-81a3ca1f4b50.png)

- [x] Added titles wherever necessary, broke down bug paragraphs into segmented sentences:
 **Before:**
![image](https://user-images.githubusercontent.com/28871211/87862818-c44ba280-c971-11ea-840c-5b423c9032fe.png)
**After:**
![image](https://user-images.githubusercontent.com/28871211/87862801-a120f300-c971-11ea-8931-a6157e1d1768.png)

- [x] Added alt. text, title and labels to all images + reference images being displayed within text context. Alt. texts and titles help when screen is being used in reader mode, or when the internet/browser is slow and HTML takes time to render the images (in this case the alt. text will be displayed on the screen)
**Title + Alt. Text (on inspect element):**
![image](https://user-images.githubusercontent.com/28871211/87862861-32906500-c972-11ea-884c-e8dab3079407.png)
**Label:**
![image](https://user-images.githubusercontent.com/28871211/87862842-0248c680-c972-11ea-836f-59b09e5e6ca8.png)

- [x] Removed Plagiarism
**Before:** 
![image](https://user-images.githubusercontent.com/28871211/87862886-7aaf8780-c972-11ea-8f62-e69b703fed36.png)
**After:**
![image](https://user-images.githubusercontent.com/28871211/87862893-8602b300-c972-11ea-9c22-24420213914e.png)

**NOTE:** Only used the accessibility guidelines revelant to the content type on this page. Other accessibility guidelines can also be incoorporated based on content criteria like presence of tables, videos (transcipts), etc. All of these guidelines can be compiled into a single reference style guide as part of GSOD2020.

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2020-07-22 15:57 UTC, Dishebh commented on docs/ClockSignalAndTriggering.md
> +<div style="text-align:center"><img title="Train of pulses with inequal ON time and OFF time" src="../assets/images/train_of_pulses.jpg" alt="A train of pulses with inequal ON time and OFF time, havi
Please check the typo CI warnings.

2020-07-22 15:58 UTC, Dishebh requested changes

2020-07-22 15:58 UTC, Dishebh commented on docs/ClockSignalAndTriggering.md
> +The type of edge triggering used when a sequential circuit is acitve only when the clock signal is transitioning from its logic high state to its logic low state.
Please check the typo CI warning

2020-09-21 16:21 UTC, tachyons commented
Changing to new urls can be tricky as all the old links to this page will start showing 404

2026-05-26 15:45 UTC, magic-peach commented
This PR has been open since 2019-2020 and the repo has changed significantly since then. Closing as stale.

2026-05-26 15:45 UTC, closed without merging