Update default.html
CircuitVerse/Interactive-Book pull request #477
Opened 2020-10-10 12:28 UTC by yuktibagrodia

A meaningful title for PR, not like: made changes to xyz.md

Fixes #

Ref #

#### Changes done:
- [x] Task 1

#### Screenshots

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [ ] Checked to see if a similar PR has already been opened 🤔️
- [ ] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

2020-11-08 14:33 UTC, Shivansh2407 requested changes

2020-11-08 14:33 UTC, Shivansh2407 commented on _layouts/default.html
> +                <button class="button" type="button" id="sidebarCollapse" class="btn btn-info new mr-3">
There is already a Class Attribute Mentioned in the Button Tag, Please do add this button class in it. Also please add the before and after screenshots to show the difference.

2021-01-10 12:52 UTC, Vishal-raj-1 commented
@yuktibagrodia Any update ? Do you want to do this. I think you just need to  `<button type="button" id="sidebarCollapse" class="btn btn-info new mr-3 button">`

2021-01-11 10:36 UTC, yuktibagrodia commented
@Vishal-raj-1 you can go-ahead

2021-01-11 11:20 UTC, Vishal-raj-1 commented
> @Vishal-raj-1 you can go-ahead

Thanks for your reply!!

2021-06-02 17:24 UTC, closed without merging