changed css styles
CircuitVerse/Interactive-Book pull request #488
Opened 2020-11-08 19:42 UTC by anushri20

CSS Styles for the new version GSoD2020

Fixes #475 

#### Changes done:
- [x] Changes in custom.scss and markdown files

#### Screenshots
Old 
![image](https://user-images.githubusercontent.com/49443274/98482307-92af5d80-2226-11eb-9342-6d02d26c0795.png)

New
![image](https://user-images.githubusercontent.com/49443274/98482364-e91c9c00-2226-11eb-8588-377aac80c94c.png)

#### Preview Link(s):  http://localhost:4000/docs/binary-representation/binary-numbers.html

#### ✅️ By submitting this PR, I have verified the following

- [ x] Checked to see if a similar PR has already been opened 🤔️
- [ x] Reviewed the contributing guidelines 🔍️
- [x ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x ] Tried Squashing the commits into one

2021-02-19 15:01 UTC, manjotsidhu commented
@anushri20 are you active to work further on this PR ?

2021-02-21 04:51 UTC, manjotsidhu commented
We have to fix more stuff in this PR, therefore I would be extending this PR to incorporate the enhancements.

2021-02-21 05:08 UTC, anushri20 commented
@manjotsidhu  Hi, yes i am active to work further on this PR.

2021-02-21 05:09 UTC, manjotsidhu commented
> @manjotsidhu Hi, yes i am active to work further on this PR.

Great, first you can rebase your changes as there are a lot of updates on that branch.

2021-02-21 05:16 UTC, manjotsidhu requested changes

2021-02-21 05:16 UTC, manjotsidhu commented on Gemfile.lock
>      ethon (0.12.0)
Please exclude changes done in this file

2021-02-21 05:24 UTC, manjotsidhu commented
Add `.text-delta` class to `utils/create_project.py`, line 44 and line 53.

2021-02-21 06:29 UTC, anushri20 commented
Okay.

2021-02-21 10:31 UTC, Shivansh2407 commented
@manjotsidhu @anushri20 you can work and get this PR done soon, in order to complete the CSS fixes for the GSOD 2020. Let me know if you have any issues/doubts! Happy Contributing 🎉

2021-02-22 06:58 UTC, manjotsidhu commented
@anushri20 Can we get updates on this ?

2021-02-22 07:03 UTC, anushri20 commented
@manjotsidhu Sure, I will make all the changes , but I am busy right now due to college. So can I do it after two days?

2021-02-22 07:09 UTC, manjotsidhu commented
> @manjotsidhu Sure, I will make all the changes , but I am busy right now due to college. So can I do it after two days?

Actually there a lot of CSS changes we need to complete. I can make a seperate Pull Request and proceed further on top of your changes. Is it fine on your end ?

2021-02-22 07:13 UTC, anushri20 commented
> 
> 
> > @manjotsidhu Sure, I will make all the changes , but I am busy right now due to college. So can I do it after two days?
> 
> Actually there a lot of CSS changes we need to complete. I can make a seperate Pull Request and proceed further on top of your changes (including authorship). Is it fine on your end ?

Okay, let me see. These are the only changes that you need?

2021-02-22 07:35 UTC, anushri20 commented
@manjotsidhu I have made the above changes, please let me know if there are any other changes. Thank you

2021-02-22 07:44 UTC, manjotsidhu commented
@anushri20 there are merge conflicts since this PR is old. You need to fix these conflicts, exclude `Gemfile.lock`, and fix hound issues.

2021-02-22 07:49 UTC, anushri20 commented
> 
> 
> @anushri20 there are merge conflicts since this PR is old. You need to fix these conflicts, exclude `Gemfile.lock`, and fix hound issues.

i can't find any conflicts or issue. Is it fine if i just create a new PR?

2021-03-03 13:18 UTC, manjotsidhu commented
@Shivansh2407 Should be closed since #516 merged.

2021-03-07 15:00 UTC, manjotsidhu commented
Can be closed, superseded by #528

2021-03-11 06:41 UTC, manjotsidhu commented
> Can be closed, superseded by #528

@Shivansh2407

2021-03-11 09:31 UTC, Shivansh2407 commented
> 
> 
> Can be closed, superseded by #528

2021-03-11 09:31 UTC, closed without merging