added pop quiz to doc/binary-algebra
CircuitVerse/Interactive-Book pull request #508
Opened 2021-02-15 09:12 UTC by ritik307

Added Pop Quiz in the `doc/binary-algebra`

Fixes #502 #491

#### Changes done:
- [x] Pop Quiz in `addition.md`
- [x] Pop Quiz in `subtraction.md`
- [x] Pop Quiz in `multiplication.md`
- [x] Pop Quiz in `division.md`
- [x] Pop Quiz in `boolean-algebra.md`
- [x] Pop Quiz in `boolean-function.md`

#### Screenshots
![addation](https://user-images.githubusercontent.com/22374829/107926392-a7c12880-6f9b-11eb-93b4-cde3571a9b2d.PNG)
![subtraction](https://user-images.githubusercontent.com/22374829/107926405-abed4600-6f9b-11eb-9fc6-ba6e803262fd.PNG)
![multiplication](https://user-images.githubusercontent.com/22374829/107926415-b0b1fa00-6f9b-11eb-8a78-159839a8f814.PNG)
![division](https://user-images.githubusercontent.com/22374829/107926424-b3acea80-6f9b-11eb-84bf-5bcddca7b398.PNG)
![boolean-algebra](https://user-images.githubusercontent.com/22374829/107926442-ba3b6200-6f9b-11eb-94c4-860995f92e28.PNG)
![boolean-func](https://user-images.githubusercontent.com/22374829/107926448-bc052580-6f9b-11eb-86b3-9dda80afda1a.PNG)

#### Preview Link(s): `doc/binary-algebra`

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2021-02-15 15:41 UTC, ritik307 commented
@Shivansh2407  will you please review my PR.

2021-02-16 07:57 UTC, Shivansh2407 requested changes
@ritik307 Great Work 🎉 But as mentioned [here](https://github.com/CircuitVerse/Interactive-Book/issues/505#issuecomment-779649640) you need to take care of the duplicate questions present on the web. Please update the PR and we'll be ready to merge!

2021-02-16 08:32 UTC, ritik307 commented
Sure will look into that and let you know when it's done

2021-02-16 09:02 UTC, ritik307 commented
@Shivansh2407 I have updated all the questions. Please look into that.

2021-03-07 15:22 UTC, manjotsidhu requested changes

2021-03-07 15:22 UTC, manjotsidhu commented on docs/binary-algebra/addition.md
> +1. What is the answer to `1100` + `0011`=?
Space before "?" is required at all occurances.

2021-03-07 15:22 UTC, manjotsidhu commented on docs/binary-algebra/boolean-algebra.md
> +1. Which amoung the following states DeMorgan’s theorem ?
Typo
```suggestion
1. Which among the following states DeMorgan’s theorem ?
```

2021-03-07 15:22 UTC, manjotsidhu commented on docs/binary-algebra/addition.md
> +2. `11111111`+`00100000`=`100011111` an example of `______`
```suggestion
2. `11111111` + `00100000` = `100011111` is an example of `______`
```

2021-03-07 15:22 UTC, manjotsidhu commented on docs/binary-algebra/boolean-functions.md
> +2. SOP(Sum of Product) is referred as `________`?
```suggestion
2. SOP (Sum of Product) is referred as `________`?
```

2021-03-07 15:22 UTC, manjotsidhu commented on docs/binary-algebra/division.md
> +1. Perform divison of the binary numbers: `1010101` by `101 `= ?
```suggestion
1. Perform divison of the binary numbers: `1010101` by `101` = ?
```

2021-04-05 14:49 UTC, ritik307 commented
@Shivansh2407 Done! Plz reivew

2021-04-08 04:38 UTC, Shivansh2407 approved these changes
Nice work @ritik307 🎉

2021-04-08 04:38 UTC, merged