pop quiz added in (docs/comb-msi/mux-demux.md)
CircuitVerse/Interactive-Book pull request #509
Opened 2021-02-15 09:41 UTC by ayan-biswas0412

A meaningful title for PR, not like: made changes to xyz.md

Fixes #505 

#### Changes done:
- [x]  pop quiz added in (docs/comb-msi/mux-demux.md)

#### Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52851184/107929688-05f00a80-6fa0-11eb-88e3-7643e5bf665f.png">

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2021-02-15 09:43 UTC, ayan-biswas0412 commented
@Shivansh2407 can you please Review this

2021-02-15 15:17 UTC, Shivansh2407 requested changes
Awesome Work Done @ayan-biswas0412 . I would here again want you to keep the options in a single line rather than entering a new line.

2021-02-15 15:22 UTC, ayan-biswas0412 commented
> Awesome Work Done @ayan-biswas0412 . I would here again want you to keep the options in a single line rather than entering a new line.

yes I have the same question in mind too , but will there be any option to doing that like there are two possibilities I have to change the codebase for the styling or I have to give smaller options such that they fit but again in mobile devices they will be in multiline , so what can I do now ?

2021-02-15 18:53 UTC, ayan-biswas0412 commented
@Shivansh2407 I have fixed the multiline options for this PR 
Screenshot
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/52851184/107984100-2befcc00-6fed-11eb-8092-caad8b35d696.png">

2021-03-07 15:26 UTC, manjotsidhu approved these changes

2021-03-07 15:26 UTC, manjotsidhu commented on docs/comb-msi/mux-demux.md
> +   *  Both MUX and DEMUX
For conserving more space
```suggestion
   *  Both MUX & DEMUX
```

2021-03-07 15:31 UTC, ayan-biswas0412 reviewed
all necessary changes done

2021-03-07 15:32 UTC, manjotsidhu approved these changes

2021-04-05 14:13 UTC, Shivansh2407 approved these changes
Great work @ayan-biswas0412 🎉

2021-04-05 14:14 UTC, merged