pop quizzes added to mux-functions.md
CircuitVerse/Interactive-Book pull request #510
Opened 2021-02-15 14:41 UTC by ayan-biswas0412

A meaningful title for PR, not like: made changes to xyz.md

Fixes #505 

#### Changes done:
- [x] pop quizzes added to mux-functions.md

#### Screenshots
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52851184/107959864-eff73f80-6fc9-11eb-9f59-5b00b19e2125.png">

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2021-02-21 14:33 UTC, ayan-biswas0412 commented
@Shivansh2407 review please

2021-03-07 15:30 UTC, manjotsidhu commented on docs/comb-msi/mux-functions.md
> +  3. Which of the following option is correct regarding MUX-based gates ?
Question can be rephrased as something like "Select the MUX-based gates which is/are possible"

2021-03-07 15:33 UTC, ayan-biswas0412 commented on docs/comb-msi/mux-functions.md
> +  3. Which of the following option is correct regarding MUX-based gates ?
```suggestion
  3. Select the MUX-based gates which is/are possible
```

2021-03-07 15:41 UTC, ayan-biswas0412 commented
@manjotsidhu please review I have made the necessary Changes

2021-03-07 15:53 UTC, manjotsidhu requested changes

2021-03-07 15:53 UTC, manjotsidhu commented on docs/comb-msi/mux-functions.md
> +     * MUX-based XOR gate is impossible
is impossible in answers is not required
```suggestion
     * MUX-based XOR gate is impossible
```

2021-03-07 16:04 UTC, manjotsidhu approved these changes

2021-04-05 14:12 UTC, Shivansh2407 approved these changes
Nice Work @ayan-biswas0412 🎉 Make sure to squash the commits before finalizing the PR for review. Thanks a lot!

2021-04-05 14:12 UTC, merged

2021-04-05 14:27 UTC, ayan-biswas0412 commented
> Nice Work @ayan-biswas0412 🎉 Make sure to squash the commits before finalizing the PR for review. Thanks a lot!

yah sure