[GSocD2020] Fix Broken Navigation buttons due to new structure
CircuitVerse/Interactive-Book pull request #511
Opened 2021-02-19 06:35 UTC by manjotsidhu

With the new structure, the logic for finding previous and next links had to be changed.
This Pull Request fixes the broken previous navigation buttons in both top and bottom button bars.
Please bear with the styling, that would be done in a separate PR due to #475  

The code for prev_next.html is based on https://github.com/pmarsceill/just-the-docs/blob/master/_includes/nav.html.
Assigned `nav_order` of 1000 to Guidelines pagesince other pages are already in the range of 100s.

Fixes #476 
Ref #460 

#### Changes done:
- [x] Fixed Broken Navigation buttons due to new structure
- [x]  Changed `nav_order` of Guidelines page for new pages.

#### Screenshots
![image](https://user-images.githubusercontent.com/22657113/108466088-1ad2e380-72a9-11eb-90bd-08c5837b7faa.png)

#### Preview Link(s): 
https://unruffled-sammet-5acbc2.netlify.app/
https://unruffled-sammet-5acbc2.netlify.app/docs/binary-representation/number-bases.html
(Navigation is best experienced when run in localhost because of link changes)

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2021-02-19 15:08 UTC, manjotsidhu commented
@Shivansh2407 Can you get this Pull Request reviewed. I am planning to get GSoD2020 changes merged with all the issues fixed, so that we can accept further contributions on Interactive Book. There's a lot of contributors out there that are waiting to get GSoD2020 branch merged.

2021-02-20 09:28 UTC, Shivansh2407 requested changes
@manjotsidhu great work done here 🎉 I wanted to request a small fix here, that whenever any section for example : Binary Representation ends, there is no next button to navigate to the next section that is Discrete Quantities. We should provide a next section button at the last page of every section (In this case Discrete Quantities page should have a Previous and Next section Button). Rest all looks good to me!

2021-02-20 10:04 UTC, manjotsidhu commented
@Shivansh2407 I presumed that the nav buttons are only for sections inside chapters.

For switching chapters, you need to be on parent chapter page and then next/previous buttons will let you directly jump from section to section.

2021-02-20 16:35 UTC, manjotsidhu commented
@Shivansh2407 Requested changes has been made, kindly review

> @manjotsidhu great work done here 🎉 I wanted to request a small fix here, that whenever any section for example : Binary Representation ends, there is no next button to navigate to the next section that is Discrete Quantities. We should provide a next section button at the last page of every section (In this case Discrete Quantities page should have a Previous and Next section Button). Rest all looks good to me!

2021-02-21 10:11 UTC, Shivansh2407 commented
@manjotsidhu Now I am able to move to next sections using Next Button. Great Work 🎉 
I do not see a Next button on the main page and a previous button on the last (guidelines) page. Was this intentionally done? I would like you to add these too, and we'll be ready to merge this PR!

2021-02-21 10:14 UTC, manjotsidhu commented
> @manjotsidhu Now I am able to move to next sections using Next Button. Great Work 🎉
> I do not see a Next button on the main page and a previous button on the last (guidelines) page. Was this intentionally done? I would like you to add these too, and we'll be ready to merge this PR!

Index page follows a different layout and Guidelines has buttons bar disabled already. I don't know the reason but it was already done in GSoD2020 branch.

2021-02-21 10:17 UTC, Shivansh2407 approved these changes
Great Work @manjotsidhu 🎉

2021-02-21 10:17 UTC, merged

2021-02-21 10:19 UTC, manjotsidhu commented
> > @manjotsidhu Now I am able to move to next sections using Next Button. Great Work 🎉
> > I do not see a Next button on the main page and a previous button on the last (guidelines) page. Was this intentionally done? I would like you to add these too, and we'll be ready to merge this PR!
> 
> Index page follows a different layout and Guidelines has buttons bar disabled already. I don't know the reason but it was already done in GSoD2020 branch.

Correction, both Index and Guidelines page follow default layout. (Pages which use circuitverse layout will have buttons bar)

2021-02-21 10:21 UTC, Shivansh2407 commented
> 
> 
> > > @manjotsidhu Now I am able to move to next sections using Next Button. Great Work 🎉
> > > I do not see a Next button on the main page and a previous button on the last (guidelines) page. Was this intentionally done? I would like you to add these too, and we'll be ready to merge this PR!
> > 
> > 
> > Index page follows a different layout and Guidelines has buttons bar disabled already. I don't know the reason but it was already done in GSoD2020 branch.
> 
> Correction, both Index and Guidelines page follow default layout. (Pages which use circuitverse layout will have buttons bar)

@manjotsidhu Yes, they follow a specific structure which was decided during GSoD, so no worries regarding that.