added some questions in adder.md
CircuitVerse/Interactive-Book pull request #515
Opened 2021-02-21 14:32 UTC by ayan-biswas0412

A meaningful title for PR, not like: made changes to xyz.md

Fixes #505 

#### Changes done:
- [x] added some questions in adder.md and given some multi option correct questions also

#### Screenshots
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/52851184/108628215-b1f19400-747f-11eb-9fc2-b28d80b1f7e4.png">

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2021-02-21 14:33 UTC, ayan-biswas0412 commented
@Shivansh2407 please review

2021-03-08 13:48 UTC, manjotsidhu requested changes

2021-03-08 13:48 UTC, manjotsidhu commented on docs/comb-msi/adders.md
> +2. Using only which of the following gates in minimum number Half Adder circuit can be implemented?
Space before "?" is required.
```suggestion
2. Using only which of the following gates in minimum number Half Adder circuit can be implemented ?
```

2021-03-08 14:33 UTC, ayan-biswas0412 commented
@manjotsidhu please review I have done the changes

2021-03-08 14:41 UTC, manjotsidhu approved these changes

2021-03-22 13:47 UTC, Shivansh2407 approved these changes
Great Work @ayan-biswas0412 🎉

2021-03-22 13:48 UTC, merged