Feature/#505 added quiz fpga.md
CircuitVerse/Interactive-Book pull request #517
Opened 2021-02-22 13:03 UTC by Samridhi-98

Added pop quiz for **fgpa.md**  

Fixes #505 

#### Changes done:
- [x] Task 1
MCQ in the `fpga.md`

#### Screenshots
![cvs](https://user-images.githubusercontent.com/54466041/108712021-3275ca80-753c-11eb-9982-6b0aa935946d.JPG)

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2021-02-22 13:07 UTC, Samridhi-98 commented
@Shivansh2407  please review my PR.

2021-03-08 13:47 UTC, manjotsidhu requested changes

2021-03-08 13:47 UTC, manjotsidhu commented on docs/logic-design/kmaps.md
> +{
Kindly remove this

2021-03-08 13:47 UTC, manjotsidhu commented on docs/seq-lsi/fpga.md
> +2. What is the function of D flip flop in FPGA?
Space before "?" is required
```suggestion
2. What is the function of D flip flop in FPGA ?
```

2021-03-26 18:46 UTC, Samridhi-98 commented
@manjotsidhu  @Shivansh2407  resolved all conflicts.

2021-03-26 19:05 UTC, manjotsidhu commented on docs/seq-lsi/fpga.md
> +2. What is the function of D flip flop in FPGA?
Pending

2021-03-26 19:06 UTC, manjotsidhu commented on docs/logic-design/kmaps.md
> +{
This is important

2021-04-05 14:10 UTC, Shivansh2407 approved these changes
Great work @Samridhi-98 🎉 Please make sure you remember squashing the commits! Thanks a lot 👍

2021-04-05 14:11 UTC, merged