Feature/#505 add quiz flowdiagram
CircuitVerse/Interactive-Book pull request #518
Opened 2021-02-22 13:08 UTC by ritik307

Added Pop Quiz in the `docs/seq-design`

Fixes #505 

#### Changes done:
- [x] Pop Quiz in `flow-diagram.md`.

#### Screenshots
![Flowchart](https://user-images.githubusercontent.com/22374829/108712618-0b6bc880-753d-11eb-8261-1813ae4ba16a.PNG)

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2021-02-22 13:52 UTC, ritik307 commented
@Shivansh2407  plz review my PR

2021-03-08 13:50 UTC, manjotsidhu requested changes

2021-03-08 13:50 UTC, manjotsidhu commented on docs/seq-design/flow-diagrams.md
> +   1. rectangular box
First letter must be capital of every option

2021-04-05 14:42 UTC, ritik307 commented
@Shivansh2407 Done! Plz review

2021-04-05 14:43 UTC, manjotsidhu commented
> @Shivansh2407 Done! Plz review

Remove unnecessary changes please.

2021-04-05 16:28 UTC, ritik307 commented
Done!

2021-05-21 06:42 UTC, manjotsidhu requested changes
Remove Unnecessary quotes like ```

2021-05-22 06:51 UTC, merged