Feature/#505 add quiz fsm
CircuitVerse/Interactive-Book pull request #520
Opened 2021-02-23 09:44 UTC by ritik307

Added Pop Quiz in the `docs/seq-design`

Fixes #505 

#### Changes done:
- [x] Pop Quiz in `fsm.md`

#### Screenshots
![FSM](https://user-images.githubusercontent.com/22374829/108825865-8f7b8a00-75e9-11eb-822a-bb0f3ec59a3c.PNG)

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2021-02-23 09:45 UTC, ritik307 commented
@Shivansh2407  plz review this PR

2021-03-11 10:07 UTC, ayan-biswas0412 requested changes
bigger options with repeated strings I think I doesn't give a good visual aspect rather try to give some smaller options keeping the meaning same and I have also mentioned some of changes please change the question no 4 also in similar way and please insert another question such that Total number becomes 5

2021-03-11 10:07 UTC, ayan-biswas0412 commented on docs/seq-design/fsm.md
> +3. Finite State Machine is said to be `Mealy state machine`?
```suggestion
3. In `Mealy state machine` the outputs depends on ?
```

2021-03-11 10:07 UTC, ayan-biswas0412 commented on docs/seq-design/fsm.md
> +   1. Outputs depend on present inputs & present states.
```suggestion
   1. on present inputs & present states.
```

2021-03-11 10:07 UTC, ayan-biswas0412 commented on docs/seq-design/fsm.md
> +   * Outputs depend only on present states.
```suggestion
   * Only on present states.  
```

2021-03-11 10:07 UTC, ayan-biswas0412 commented on docs/seq-design/fsm.md
> +3. Finite State Machine is said to be `Moore state machine`?
make same changes Here also

2021-03-11 10:17 UTC, ritik307 commented
@ayan-biswas0412 thanks for reviewing the code will do all the mentioned changes ASAP.

2021-04-05 14:17 UTC, Shivansh2407 commented
> 
> 
> @ayan-biswas0412 thanks for reviewing the code will do all the mentioned changes ASAP.

@ritik307 could you please make the specified changes so that we can merge this PR. Thanks a lot!

2021-04-05 14:28 UTC, ritik307 commented
@Shivansh2407 Done! please review

2021-04-18 19:34 UTC, ayan-biswas0412 requested changes
remove unnecessary spaces from the files in which you have changed nothing

2021-05-22 07:01 UTC, manjotsidhu commented
Closing this Pull Request since it's not active. You can make a new Pull Request anytime with the changes. Thanks for the contribution.

2021-05-22 07:01 UTC, closed without merging