Added quiz in microprocessors.md
CircuitVerse/Interactive-Book pull request #521
Opened 2021-02-23 10:40 UTC by Samridhi-98

Added pop quiz in microprocessors.md

Fixes #505 

#### Changes done:
- [x] Task 1
MCQ for `microprocessor.md` 

#### Screenshots
![cvs](https://user-images.githubusercontent.com/54466041/108832425-8abad400-75f1-11eb-9207-b4f1f603b4a2.JPG)

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2021-02-23 10:42 UTC, Samridhi-98 commented
@Shivansh2407 please review my PR

2021-03-08 13:53 UTC, manjotsidhu requested changes
Please remove the unnecessary changes (newlines) in other files. Let's keep PRs neat and tidy.

2021-03-08 13:53 UTC, manjotsidhu commented on docs/seq-lsi/microprocessors.md
> +1. Which of the following is `single-clip` microprocessors?.
Space before question is required at all occurrences
```suggestion
1. Which of the following is `single-clip` microprocessors ?
```

2021-03-26 17:07 UTC, Samridhi-98 commented
@Shivansh2407  Will you review my PR.

2021-03-26 17:29 UTC, Shivansh2407 approved these changes
Great Work @Samridhi-98 🎉 I see a lot of file changes here, merging this but make sure no extra spaces are added in any files when you make the PR

2021-03-26 17:30 UTC, merged