Added quiz for rom microcontroller
CircuitVerse/Interactive-Book pull request #522
Opened 2021-02-23 11:58 UTC by Samridhi-98

Added quiz for rom-microcontroller.md

Fixes #505 

#### Changes done:
- [x] Task 1
MCQ in `rom-microprocessor.md`

#### Screenshots
![csv](https://user-images.githubusercontent.com/54466041/108840404-4e40a580-75fc-11eb-8be6-586146b4bf06.JPG)

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [x] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [x] Tried Squashing the commits into one

2021-02-23 12:02 UTC, Samridhi-98 commented
@Shivansh2407 Please review this PR

2021-03-12 07:34 UTC, ayan-biswas0412 requested changes
1.please remove the unnecessary spaces
2. add single space before question mark in each question

2021-03-12 07:34 UTC, ayan-biswas0412 commented on docs/binary-algebra/addition.md
> +
```suggestion
```

2021-03-12 07:34 UTC, ayan-biswas0412 commented on docs/comb-ssi/universal-gates.md
> +
please remove unnecessary spaces

2021-03-12 07:34 UTC, ayan-biswas0412 commented on docs/logic-design/canonical.md
> +
here also

2021-03-12 07:34 UTC, ayan-biswas0412 commented on docs/logic-design/functional-description.md
> +
please remove this blank space lines

2021-03-12 07:34 UTC, ayan-biswas0412 commented on docs/seq-lsi/rom-microcontrollers.md
> +1. What is the ROM capacity of Counter based µcontroller?
```suggestion
1. What is the ROM capacity of Counter based µcontroller ?
```
in each of the question space before the question mark must be added

2021-03-12 07:34 UTC, ayan-biswas0412 commented on docs/seq-lsi/rom-microcontrollers.md
> +2. Which among the following is not micro-controller?
```suggestion
2. Which among the following is not micro-controller ?
```

2021-03-26 16:47 UTC, Samridhi-98 commented on docs/seq-lsi/rom-microcontrollers.md
> +2. Which among the following is not micro-controller?
@ayan-biswas0412 Made all the changes

2021-03-26 17:02 UTC, Samridhi-98 commented
@Shivansh2407  Will you review my PR.

2021-03-26 18:08 UTC, ayan-biswas0412 requested changes
please resolve the conflicts

2021-03-26 18:38 UTC, Samridhi-98 commented
@ayan-biswas0412  @Shivansh2407  conflict has been resolved

2021-04-05 14:07 UTC, Shivansh2407 approved these changes
Great work @Samridhi-98 🎉 I would suggest to squash the commits before you finalize the PR for review in future. Thank you!

2021-04-05 14:08 UTC, merged