Added Applications of MUX and DEMUX
CircuitVerse/Interactive-Book pull request #586
Opened 2021-11-24 21:21 UTC by Prerna-0202

Fixes #32 

I have added the applications of multiplexer and demultiplexer to make the book more informative.

#### Screenshots
![Screenshot (5)](https://user-images.githubusercontent.com/89515816/143314145-d4a8e2f1-2370-410e-bec5-7f9e95653c4d.png)
![Screenshot (6)](https://user-images.githubusercontent.com/89515816/143314261-6fd56bbf-def7-4de7-9346-e89a4a8a9e0b.png)

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [ ] Checked to see if a similar PR has already been opened 🤔️
- [ ] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

2021-11-24 21:23 UTC, Prerna-0202 commented
@manjotsidhu, Can you please review my pr once and provide me with the reviews...

2021-11-25 05:55 UTC, manjotsidhu requested changes

2021-11-25 07:14 UTC, Prerna-0202 commented
@manjotsidhu, I have commit the changes. Can you please review it again...

2021-11-25 07:16 UTC, manjotsidhu commented on docs/comb-msi/mux-demux.md
> +• Computer Memory - Multiplexers are used in computer memory to maintain a huge amount of memory in the computers, and also to reduce the number of copper lines required to connect the memory to othe
Here as well

2021-11-25 07:16 UTC, manjotsidhu commented on docs/comb-msi/mux-demux.md
> +• Computer Memory - Multiplexers are used in computer memory to maintain a huge amount of memory in the computers, and also to reduce the number of copper lines required to connect the memory to othe
Make changes everrywhere

2021-11-25 07:17 UTC, Prerna-0202 commented on docs/comb-msi/mux-demux.md
> +• Computer Memory - Multiplexers are used in computer memory to maintain a huge amount of memory in the computers, and also to reduce the number of copper lines required to connect the memory to othe
@manjotsidhu, Done sir!!!

2021-11-25 08:15 UTC, manjotsidhu approved these changes

2021-11-25 08:15 UTC, merged