Solved Boolean algebra interactive element issue
CircuitVerse/Interactive-Book pull request #599
Opened 2021-12-18 12:00 UTC by Palaksharma23

Fixes #556 
Fixes #581

#### Changes done:
- [] Task 1 I have made switches visible on reload 
- []  Task 2 I have also solved the issue of not getting a switch while selecting not gate 

#### Screenshots

![image](https://user-images.githubusercontent.com/87171452/146640160-cd46aa35-93a9-4806-a142-d733ba994897.png)

https://user-images.githubusercontent.com/87171452/146640179-a735b697-41bf-496e-a4d3-4071734ef455.mp4

#### ✅️ By submitting this PR, I have verified the following

- [ yes ] Checked to see if a similar PR has already been opened 🤔️
- [ yes ] Reviewed the contributing guidelines 🔍️
- [ yes  ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ yes ] Tried Squashing the commits into one

2021-12-18 12:01 UTC, Palaksharma23 commented
@manjotsidhu can you please once review my pull request .

2021-12-19 14:13 UTC, ayan-biswas0412 approved these changes
Good work @Palaksharma23 🎉
@manjotsidhu can we merge this? 
it is working fine according to me.

2021-12-21 13:29 UTC, manjotsidhu commented
@ayan-biswas0412 can you check #531 issue in your safari ?

2021-12-21 14:51 UTC, Palaksharma23 commented
@manjotsidhu no sir sorry it is just ref to #531 i will update my first comment.

2021-12-21 14:52 UTC, Palaksharma23 commented
Done sir :)

2021-12-21 14:59 UTC, manjotsidhu requested changes

2021-12-21 14:59 UTC, manjotsidhu commented on _includes/bool.html
> +    <div id="0_bool" style="background-image: url(/assets/images/switch_on.png);" class="switch" onClick="toggle_switch(0);"></div>
Avoid inline CSS and prefer already used css/id selectors in internal CSS.

2021-12-31 07:37 UTC, Palaksharma23 commented
@manjotsidhu okay sir i will commit it asap :)

2022-01-10 10:54 UTC, Palaksharma23 commented
done sir :) @manjotsidhu

2022-01-12 04:28 UTC, manjotsidhu approved these changes
Good work 👍

2022-01-12 04:29 UTC, merged