Corrected the karnaugh Map Table
CircuitVerse/Interactive-Book pull request #601
Opened 2021-12-21 18:43 UTC by Prerna-0202

Fixes #28 

Ref #461 

#### Changes done:
I have corrected the values in karnaugh Map table as mentioned in issue#28 for all  the input values of k  ...
- [x] Task 1

#### Screenshots
Before:-
![Screenshot (85)](https://user-images.githubusercontent.com/89515816/146980987-c214d63d-1292-4190-826b-cc76a8161b70.png)
![Screenshot (84)](https://user-images.githubusercontent.com/89515816/146981003-fc2666b3-052d-4c55-990f-763e119e6317.png)

After:-
![Screenshot (82)](https://user-images.githubusercontent.com/89515816/146981686-0f10b760-7171-4987-af3c-c10fd0574f35.png)
![Screenshot (83)](https://user-images.githubusercontent.com/89515816/146981701-6c92ab67-d192-4699-8306-24b424c66f99.png)

#### ✅️ By submitting this PR, I have verified the following

- [ ] Checked to see if a similar PR has already been opened 🤔️
- [ ] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

2021-12-21 18:46 UTC, Prerna-0202 commented
@manjotsidhu, Can you please review my pr once...

2021-12-22 05:46 UTC, manjotsidhu requested changes
Is it possible to implement this without needing to hardcode the tables ? The previous implementation though broken had less lines of code and was scalable.

2021-12-22 14:18 UTC, Prerna-0202 commented
> Is it possible to implement this without needing to hardcode the tables ? The previous implementation though broken had less lines of code and was scalable.

Okay, I will try to do it in that way...

2021-12-27 07:52 UTC, ayan-biswas0412 requested changes
Is there any way to generate the numbers without hardcoding them? @Prerna-0202

2022-01-03 11:29 UTC, Prerna-0202 commented
@manjotsidhu @ayan-biswas0412, I have tried but not getting any other way to do this without hardcoding the tables...If you have any idea please share...

2022-01-06 07:23 UTC, manjotsidhu commented
@vedant-jain03 can you help @Prerna-0202 with this ?

2022-01-06 08:07 UTC, vedant-jain03 commented
> @vedant-jain03 can you help @Prerna-0202 with this ?

Yeah sure, I think we can fill the array of each by recognizing the pattern. Provide me some time for recognizing the pattern.

2023-02-16 11:46 UTC, Malavi1 commented
In parallel I will also try to figure out the pattern behind this

2026-05-26 15:45 UTC, magic-peach commented
This PR has been open since 2021-2022 with no activity since. Closing as stale.

2026-05-26 15:45 UTC, closed without merging