Added a feature to take notes using localstorage Fixes #609
CircuitVerse/Interactive-Book pull request #611
Opened 2022-01-26 19:00 UTC by Palaksharma23

Fixes #609 
 
#### Screenshots

## Finally
![image](https://user-images.githubusercontent.com/87171452/151228713-93532a03-0be9-462c-b815-7f685f00165f.png)

#### ✅️ By submitting this PR, I have verified the following

- [✅️] Checked to see if a similar PR has already been opened 🤔️
- [✅️] Reviewed the contributing guidelines 🔍️

2022-02-05 04:31 UTC, ayan-biswas0412 requested changes
![image](https://user-images.githubusercontent.com/52851184/152628684-3d1734b6-8d74-4f85-877c-19d9534297ef.png)
I think if we can have the notes at the place where a user has selected a text that will be much helpful.

Like according to me the user end flow must be like this 
user select a text -> notes button visible -> notes pad inserted at the place where user has selected the text

2022-02-05 04:37 UTC, Palaksharma23 commented
> ![image](https://user-images.githubusercontent.com/52851184/152628684-3d1734b6-8d74-4f85-877c-19d9534297ef.png) I think if we can have the notes at the place where a user has selected a text that will be much helpful.
> 
> Like according to me the user end flow must be like this user select a text -> notes button visible -> notes pad inserted at the place where user has selected the text

yes sir @ayan-biswas0412 this is a great idea 💡 I will commit this asap
just one query that when a user take notes by selecting the text where should that note be display at the end of the page or inline with the text or on the right side of the page

2022-02-05 05:00 UTC, ayan-biswas0412 commented
> > ![image](https://user-images.githubusercontent.com/52851184/152628684-3d1734b6-8d74-4f85-877c-19d9534297ef.png) I think if we can have the notes at the place where a user has selected a text that will be much helpful.
> > Like according to me the user end flow must be like this user select a text -> notes button visible -> notes pad inserted at the place where user has selected the text
> 
> yes sir @ayan-biswas0412 this is a great idea 💡 I will commit this asap just one query that when a user take notes by selecting the text where should that note be display at the end of the page or inline with the text or on the right side of the page

Actually what happens in google docs commenting system, that's same i was suggesting.
Ref : [Google Docs Comments](https://support.google.com/docs/answer/65129?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cadd-a-comment)

2026-05-26 15:45 UTC, magic-peach commented
This PR has been open since 2021-2022 with no activity since. Closing as stale.

2026-05-26 15:45 UTC, closed without merging