Scroll-to-top button missing from Guidelines
CircuitVerse/Interactive-Book pull request #669
Opened 2024-01-21 15:43 UTC by antriksh-9

A meaningful title for PR, not like: made changes to xyz.md

Fixes #666 

#### Changes done:
- [x]Added the "Scroll-to-top button" that was previously missing from the "Guidelines" and "About" section on the [website](https://learn.circuitverse.org/).
Also added the "Sidebar", "Previous", and "Next" buttons that were previously missing from both the sections.

#### Screenshots

#### Preview Link(s): 

#### ✅️ By submitting this PR, I have verified the following

- [x] Checked to see if a similar PR has already been opened 🤔️
- [x] Reviewed the contributing guidelines 🔍️
- [ ] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [ ] Tried Squashing the commits into one

2024-01-21 16:27 UTC, Arnabdaz requested changes

2024-01-21 16:27 UTC, Arnabdaz commented on Gemfile.lock
remove the changes in lock file

2024-01-21 16:39 UTC, antriksh-9 commented on Gemfile.lock
Hey @Arnabdaz I have removed the changes.

2024-01-21 17:40 UTC, Arnabdaz approved these changes
LGTM :+1: 
cc @tachyons

2026-05-26 15:51 UTC, magic-peach commented
No activity on this PR in over a year and the codebase has moved. Closing as stale.

2026-05-26 15:51 UTC, closed without merging

2026-05-26 15:52 UTC, magic-peach commented
No activity on this PR in over a year and the codebase has moved. Closing as stale.