(fix: #670): Copyright year is outdated it should be updated from `2023` to `2024`
CircuitVerse/Interactive-Book pull request #671
Opened 2024-01-24 07:28 UTC by subhamkumarr

- use "Fixes" only when the pull request completely satisfies the issue

## Fixes: Outdated copyright year is  updated from `2023` to `2024`

## Screenshots 

### Before Change:
![WhatsApp Image 2024-01-24 at 12 56 55_b94d7145](https://github.com/CircuitVerse/Interactive-Book/assets/99977240/2eda5d61-45d6-452a-9f0f-c39bdc789a41)

### After changes:
![Screenshot (1036)](https://github.com/CircuitVerse/Interactive-Book/assets/99977240/d2a23832-c539-43a1-b923-187b282748d9)

#### ✅️ By submitting this PR, I have verified the following
- [X] Checked to see if a similar PR has already been opened 🤔️
- [X] Reviewed the contributing guidelines 🔍️
- [X] Sample preview link added (add the link(s) for all the pages changed/updated from the checks tab after checks complete)
- [X] Tried Squashing the commits into one

2024-01-26 17:36 UTC, subhamkumarr commented
@tanmoysrt sir, i raised this 2days ago could you please review this?

2024-01-26 18:38 UTC, tanmoysrt requested changes

2024-01-26 18:38 UTC, tanmoysrt commented on package-lock.json
> +}
```suggestion
```

Delete this file

2024-01-26 19:03 UTC, subhamkumarr commented on package-lock.json
> +}
@tanmoysrt  Done the changes Sir.

2024-01-27 07:18 UTC, subhamkumarr commented on package-lock.json
> +}
@tanmoysrt Done the changes sir.

2024-01-31 20:38 UTC, subhamkumarr commented
@tanmoysrt  i made the changes.

2024-02-03 06:39 UTC, subhamkumarr commented
@tanmoysrt @tachyons Could you please review this PR

2024-02-03 16:16 UTC, tachyons approved these changes

2024-02-03 16:17 UTC, merged